# Generated by Django 6.0.3 on 2026-03-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('year', models.CharField(db_index=True, max_length=10)),
                ('data_type', models.CharField(db_index=True, max_length=20)),
                ('file', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'data_type', 'year'], name='chatbot_tra_country_7433c3_idx')],
            },
        ),
    ]
